name: Executar Testes JUnit
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Baixar o JUnit e Rodar os Testes
      run: |
        wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.2/junit-platform-console-standalone-1.10.2.jar
        javac -cp junit-platform-console-standalone-1.10.2.jar PessoaTest.java
        java -jar junit-platform-console-standalone-1.10.2.jar --class-path . --select-class PessoaTest
        
